version: "3.9"
services:
  app:
    image: "simple-grpc-crud:1.0"
    ports:
      - "8080:8080"
    networks:
      sc-net:
    depends_on: [
      database
    ]
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-cs:/var/lib/postgresql/data
    networks:
      sc-net:

volumes:
  db-cs:
networks:
  sc-net: